name: proteomics

channels:
  - conda-forge
  - anaconda

dependencies:
  - python=3.7
  - openjdk=8.0
  - pyspark=2.4
#  - py4j=0.10.7
  - biopython=1.72
  - numba=0.49
  - jupyterlab=3.2
  - ipywidgets=7.6
  - py3Dmol=0.8
  - py2neo
  - monotonic
  - black
  - pip
  - pip:
    - gql
    - git+https://github.com/sbl-sdsc/mmtf-pyspark.git 
